version: 2
jobs:
  test-python3:
    docker:
      - image: circleci/python:3.6.1
      
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "test-requirements.txt" }}
          - v1-dependencies-

      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install -r test-requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "test-requirements.txt" }}
        
      - run:
          name: Check style
          command: |
            . venv/bin/activate
            flake8

  test-python2:
    docker:
      - image: circleci/python:2.7.14

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-py2-{{ checksum "requirements.txt" }}-{{ checksum "test-requirements.txt" }}
          - v1-dependencies-py2-

      - run:
          name: Install Dependencies
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install -r test-requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-py2-{{ checksum "requirements.txt" }}-{{ checksum "test-requirements.txt" }}

      - run:
          name: Check style
          command: |
            . venv/bin/activate
            flake8

workflows:
  version: 2
  test:
    jobs:
      - test-python3
      - test-python2
